sudo: false
language: node_js
node_js:
  - node

before_install:
  - npm install -qg bower gulp-cli
  - npm install -q
  - bower install --force

script:
  - gulp ci

env:
  global:
    - SAUCE_USERNAME=angular-ui-mask
    - SAUCE_ACCESS_KEY=b4b4d64e-4188-4cae-a91c-29214a389c8a
